name: Tag Latest

on:
  release:
    types: [published]

jobs: 
  latest:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@master
    - name: Tag Latest Release
      uses: EndBug/latest-tag@latest
      with:
        tag-name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
